import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Les barres latérales du site.
 *
 * Deux entrées seulement, parce qu'un lecteur n'a que deux questions : « comment
 * je m'en sers ? » et « que fait exactement cette fonction ? ». Le dossier de
 * conception — arbitrages, invariants — vit à part : ce n'est pas de la
 * documentation d'usage, c'est le registre des décisions.
 */
const sidebars: SidebarsConfig = {
    guide: [
        "index",
        {
            type: "category",
            label: "Démarrer",
            collapsed: false,
            items: [
                "demarrer/le-probleme",
                "demarrer/installation",
                "demarrer/premier-formulaire",
            ],
        },
        {
            type: "category",
            label: "Le modèle",
            collapsed: false,
            items: [
                "modele/flags",
                "modele/behavior-et-validator",
                "modele/passe-interrompue",
                "modele/une-ligne-est-un-formulaire",
            ],
        },
        {
            type: "category",
            label: "Guides",
            items: [
                "guides/preremplir",
                "guides/valider",
                "guides/dependances",
                "guides/champs-repetables",
                "guides/vos-propres-flags",
            ],
        },
        {
            type: "category",
            label: "React",
            items: [
                "react/installation",
                "react/hooks",
                "react/listes",
            ],
        },
    ],

    // La référence est générée par TypeDoc : son contenu ne s'écrit pas ici, il
    // se découvre. `autogenerated` suit donc l'arborescence produite au build
    // plutôt qu'une liste que la prochaine signature rendrait fausse.
    reference: [
        // `link` sur la catégorie : sans lui, l'entrée « Référence » de la
        // barre de navigation atterrit sur la première page par ordre
        // alphabétique — `classes/Behavior` —, ce qui n'est le point d'entrée
        // de rien.
        {
            type: "category",
            label: "slz-form",
            collapsed: false,
            link: { type: "doc", id: "reference/slz-form/index" },
            items: [{ type: "autogenerated", dirName: "reference/slz-form" }],
        },
        {
            type: "category",
            label: "slz-react-form",
            collapsed: false,
            link: { type: "doc", id: "reference/slz-react-form/index" },
            items: [{ type: "autogenerated", dirName: "reference/slz-react-form" }],
        },
    ],
};

export default sidebars;
