import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Le dossier de conception, lu **en place** dans `docs/`.
 *
 * Une seule page pour l'instant — `MODEL.md` —, et c'est voulu : la découper
 * obligerait à renuméroter ses invariants, que le code cite par numéro et que
 * la règle dure 9 du skill interdit de réordonner.
 */
const sidebars: SidebarsConfig = {
    conception: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
